### ISSUE TITLE
RTC callbacks are not working

### ISSUE THREAD

**Issue by imomin** [wearefractal/holla#46]
I took test script from 0.7 and trying to get it off the ground. Looks like rtc's method doesn't hit call callback functions. Any idea? Does anybody have working demo?

rtc.register("tom", function(err) {
debugger;  //<--- It never hits the debugger;
});

holla.createFullStream(function(err, stream) {
        debugger; //<--- it hits this debugger
        rtc.createCall(function(err, call){
            debugger; //<--- but does not hit this debugger
          call.setLocalStream(stream);
          call.add("bob");
        });
      });

I'm using "socket.io": "^1.0.6" and "socket.io-client": "^1.0.6".

**Comment by imomin** [comment]
I was finally able to make it work. Can you push your 0.7 on npm?

**Comment by contra** [comment]
@imonin Can you explain what you mean?

**Comment by imomin** [comment]
When I do "npm install hallo" it downloads old version and not v0.7. I had to manually copy and paste the code. Can you please push v0.7 to node package? Thanks.

**Comment by contra** [comment]
@imomin `npm install wearefractal/holla#0.7 --save`
